---
name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CXX: g++-10

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Build&Test
        run: make junit
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        if: always()
        with:
          files: "build/junit/reports/*.xml"
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Fetch gcovr
        run: pip3 install gcovr
      - name: Generate coverage
        run: make coverage
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: build/coverage/coverage.xml
          name: codecov-eltau
          fail_ci_if_error: true
          verbose: true
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Run clang-tidy
        run: make sca
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - run: |
         make format
         # Reformatting should have made no changes.
         git diff --exit-code --stat
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: 'true'
      - name: Generate documentation
        uses: mattnotmitt/doxygen-action@v1.9.1
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
